[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
    "terrax",
    "terrax.atmosphere",
    "terrax.auxiliary",
    "terrax.core",
    "terrax.couplers",
    "terrax.inference",
    "terrax.metrics",
    "terrax.toy_model_examples",
    "terrax.training",
    "terrax.xreader",
]

[project]
name = "terrax"
description = "Terrax: Library for AI-first Earth System Modeling"
version = "0.0.5"  # keep in sync with __version__ in terrax/__init__.py
authors = [
    {name = "Google LLC", email = "noreply@google.com"},
]
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "coordax>=0.1.5",
    "dinosaur>=1.3.6",
    "einops",
    "etils",
    "fiddle>=0.3.0",
    # "fiddle @ git+https://github.com/google/fiddle.git",
    "flax>=0.12.0",
    "grain",
    "jax",
    "jax-datetime>=0.1.2",
    "jax-solar",
    "jaxlib",
    "numpy",
    "optax",
    "orbax",
    "pandas",
    "tqdm",
    "treescope",
    "xarray>=2026.4.0",
    "zarr>= 3.1.4",
]

[project.urls]
source = "https://github.com/neuralgcm/terrax"
documentation = "https://terrax.readthedocs.io"

[project.optional-dependencies]
tests = [
    "absl-py",
    "chex",
    "pytest",
]
docs = [
    "furo==2024.4.27",
    "Jinja2==3.1.4",
    "myst-nb==1.1.0",
    "myst-parser==3.0.1",
    "sphinx==7.3.7",
]